export class Historia {
    mconsulta!:string;
    eactual!:string;
    apersonales!:string;
    afamiliares!:string;
    cabeza!:string;
    cuello!:string;
    torax!:string;
    abdomen!:string;
    pelvis!:string;
    extremidades!:string;
    temp!:string;
    pa!:string;
    fc!:string;
    fr!:string;
    pu!:string;
    peso!:string;
    talla!:string;
    imc!:string;
}